---
- name: 'Import Validator'
  tags:
    - always
  ansible.builtin.import_tasks: validator/main.yml

- name: 'Import prerequisites tasks'
  ansible.builtin.import_tasks: prerequisites/main.yml

- name: 'Import firewalld tasks'
  become: true
  become_user: 'root'
  tags:
    - firewall
    - firewalld
  ansible.builtin.import_tasks: firewalld/main.yml
