---
- name: 'Prerequisites | Ensure required packages are installed'
  become: true
  become_user: 'root'
  tags:
    - always
  notify: 'Reload firewalld'
  ansible.builtin.package:
    state: present
    name: '{{ packages.requirements }}'
